name: Test ramp kit

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Initialize Python 3.9
          uses: actions/setup-python@v1
          with:
              python-version: 3.9

        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

        - name: Download data files
          run: |
              cd data/
              wget https://github.com/rth/bike_counters/releases/download/v0.1.0/test.parquet
              wget https://github.com/rth/bike_counters/releases/download/v0.1.0/train.parquet

        - name: Run ramp-test
          run: |
              ramp-test


